### ISSUE TITLE
Error when generating pkginfo

### ISSUE THREAD

**Issue by multiflexi** [jacobfgrant/munki-tap#1]
Hi,
I have an issue when trying to build a package. Maybe I am doing something wrong but I did not find any examples how to use munki-tap.
```
$ munkitap pour
brew-pkg already installed and up-to-date
varenc/ffmpeg/ffmpeg already installed and up-to-date
Building varenc/ffmpeg/ffmpeg-4.1.3-with-options.pkg
Generating pkginfo for 
Traceback (most recent call last):
  File "/usr/local/bin/munkitap", line 549, in <module>
    main()
  File "/usr/local/bin/munkitap", line 487, in main
    if not already_in_munki(pkginfo):
  File "/Library/Munkitap/munkitaplib/munki_utils.py", line 73, in <lambda>
    return lambda pkginfo : pkginfo['installer_item_hash'] in item_hashes
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by carsontyler** [comment]
Also experiencing this issue with any formula I try to pour. 
```
$ munkitap pour -f yarn
brew-pkg already installed and up-to-date
yarn in homebrew
yarn already installed and up-to-date
Building yarn-1.19.2.pkg
Generating pkginfo for 
Traceback (most recent call last):
  File "/usr/local/bin/munkitap", line 549, in <module>
    main()
  File "/usr/local/bin/munkitap", line 465, in main
    if not already_in_munki(pkginfo):
  File "/Library/Munkitap/munkitaplib/munki_utils.py", line 73, in <lambda>
    return lambda pkginfo : pkginfo['installer_item_hash'] in item_hashes
TypeError: 'NoneType' object has no attribute '__getitem__'
```
